### ISSUE TITLE
Update Messaging Upon Level Completion

### ISSUE THREAD

**Issue by roughdraftofme** [cop4934-fall19-group32/Project-32#118]
There needs to be more excitement when a player completes a level. We need to emphasize their accomplishment in completing the level and generate more praise/reward fulfillment. Update the messaging as follows:

- [x] "Good Job!" or something similar instead of "Solution Accepted"
- [x] "Next Level" or something similar instead of "Level Select"
- [ ] Tell the player how many stars they earned

**Comment by j-e-b** [comment]
" Tell the player how many stars they earned" added to Star Unlocking #121
