### ISSUE TITLE
Card Hand

### ISSUE THREAD

**Issue by j-e-b** [cop4934-fall19-group32/Project-32#16]
When a puzzle is selected that includes memory cards, the game should display those cards to the player.

- [ ] Area of the screen is reserved to play these cards
- [ ] These cards are displayed in a fan pattern
- [ ] Hovering over a card will cause it to rise out of the fan and enlarge to allow the player to take a closer look
- [ ] Dragging the card over the board and releasing will cause it to be played. From here, placement functionality will be covered by #15 

As a reference, observe how the card hands behave in [this video](https://youtu.be/ymuVLuVlsOU?t=40).

GanttStart: 2020-1-15
GanttDue: 2020-1-20

**Comment by MrLever** [comment]
The last bullet point may intensive enough to be split into a new issue. Please let me know if that is necessary.
