### ISSUE TITLE
Card Location Data

### ISSUE THREAD

**Issue by j-e-b** [cop4934-fall19-group32/Project-32#17]
- [ ] Create a way to represent the location for every card on the puzzle board.
   - [ ] Locations include the card hand and card slot indices.
   - [ ] Considers what card is at which location.
   - [ ] Should be serializable.

**Comment by MrLever** [comment]
@j-e-b Is this issue overshadowed by (or should it be merged into) #15

**Comment by MrLever** [comment]
Duplicate of #15
