### ISSUE TITLE
Actor reading input

### ISSUE THREAD

**Issue by roughdraftofme** [cop4934-fall19-group32/Project-32#40]
This will cover all of the movement and response functionality associated with the input command.

- [x] move to the input box
- [x] remove the top element from the input box and "hold" it
- [x] if the box is empty, need to react to indicate there was a problem
- [x] if already holding something, discard it in favor of the new element

**Comment by MrLever** [comment]
Also assigning @j-e-b since his code will have to support these operations. 

@j-e-b You can create a separate issue to track this functionality on your end if you'd prefer.
