### ISSUE TITLE
Actor reading output

### ISSUE THREAD

**Issue by roughdraftofme** [cop4934-fall19-group32/Project-32#41]
This will cover all of the movement and response functionality associated with the output command.

- [x] move to the output box
- [x] place the item being held into the output box
- [x] if nothing is being held, report a fault to the interpreter to halt execution

**Comment by MrLever** [comment]
Also assigning @j-e-b since his code will have to support these operations. 

@j-e-b You can create a separate issue to track this functionality on your end if you'd prefer.
