### ISSUE TITLE
Computron Level Select Sounds

### ISSUE THREAD

**Issue by MrLever** [cop4934-fall19-group32/Project-32#70]
When the user directs computron in the level select screen by clicking on a node, the move sound isn't played while computron travels between nodes.

- [ ] Route-to movement has sound effects
- [ ] WASD move commands have sound effects

**Comment by j-e-b** [comment]
Figured out how to fix this but removed the sound entirely until a new, more fitting sound is created.

**Comment by MrLever** [comment]
OBE
